# Generated by Django 3.0 on 2019-12-29 09:40

from django.db import migrations, models
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4000, verbose_name='Title')),
                ('content', simplemde.fields.SimpleMDEField(verbose_name='mardown content')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
